### ISSUE TITLE
Failed to open on Windows 11 on ARM

### ISSUE THREAD

**Issue by lennondotw** [ZYFDroid/CHRJ#1]
- Nothing happened after double click.
- No output while open in command line.

Release version: v1.0.0.0

<img width="1142" alt="Screen Shot 2021-09-30 at 19 28 00" src="https://user-images.githubusercontent.com/26853900/135447203-67a983ac-1f9d-441d-ba0d-0cbb5e10f9a8.png">

**Comment by ZYFDroid** [comment]
Fixed please try

**Comment by lennondotw** [comment]
Fixed :)
